# wandb
wandb_name: "debug_fp_sim"
# data
pth: "MassSpecGym.tsv"
split_type: "benchmark"
subsample_frac:
# output
mz_max: 1005.
mz_bin_res: 0.01
ints_transform: "sqrt"
# model
model_type: "fp"
# optimization
max_epochs: 1
# other
accelerator: "gpu"
do_retrieval: False
