# wandb
wandb_name: "debug_ret_gnn"
# data
pth: "data/MassSpecGym_small.tsv"
split_type: "benchmark"
subsample_frac: 0.1
# output
mz_max: 1005.
mz_bin_res: 0.01
ints_transform: "sqrt"
# model
model_type: "gnn"
# optimization
max_epochs: 5
# other
accelerator: "gpu"