# wandb
wandb_name: "debug_ret_gnn"
# data
pth: "data/MassSpecGym_small.tsv"
candidates_pth: "data/MassSpecGym_retrieval_candidates_mass_with_test.json"
# candidates_pth: "data/MassSpecGym_retrieval_candidates_formula_with_test.json"
split_type: "benchmark"
instrument_types: ["QTOF","Orbitrap"]
subsample_frac: 0.1
# output
mz_max: 1005.
mz_bin_res: 0.01
ints_transform: "sqrt"
# model
model_type: "gnn"
# optimization
max_epochs: 1
# other
accelerator: "gpu"