# wandb
wandb_name: "new_bench_retform_gnn"
# data
pth: "data/MassSpecGym.tsv"
candidates_pth: "data/MassSpecGym_retrieval_candidates_formula_with_test.json"
split_type: "benchmark"
# output
mz_max: 1005.
mz_bin_res: 0.01
ints_transform: "sqrt"
# model
model_type: gnn
mol_hidden_size: 256
mol_num_layers: 4
mol_gnn_type: GINE
mol_normalization: batch
mol_dropout: 0.2
mol_pool_type: mean
mlp_normalization: batch
mlp_hidden_size: 512
mlp_dropout: 0.0
mlp_num_layers: 4
mlp_use_residuals: True
ff_prec_mz_offset: 5
ff_bidirectional: True
ff_output_map_size: 256
# optimization
lr: 0.0003755
lr_schedule: True
lr_decay_rate: 0.8523
weight_decay: 0.0000001
batch_size: 128
max_epochs: 20
optimizer_type: "adamw"
gradient_clip_val: 5.0
gradient_clip_algorithm: norm
# other
accelerator: "gpu"