# wandb
wandb_name: "old_ik_fp"
# data
tsv_pth: "data/MassSpecGym.tsv"
split_type: "all_inchikey"
# output
mz_max: 1005.
mz_bin_res: 0.01
ints_transform: "sqrt"
# model
model_type: "fp"
# optimization
max_epochs: 20
# other
accelerator: "gpu"
