# wandb
wandb_entity: "adamoyoung"
wandb_project: "MSG"
wandb_name: "template"
# data
tsv_pth: "data/MassSpecGym_3.tsv"
meta_keys: ["adduct","precursor_mz","instrument_type","collision_energy"]
fp_types: ["morgan","maccs","rdkit"]
adducts: ["[M+H]+"]
instrument_types: ["QTOF","QFT","Orbitrap","ITFT"]
max_collision_energy: 200.
mz_from: 10.
mz_to: 1000.
# input
metadata_insert_location: "mlp"
collision_energy_insert_size: 16
adduct_insert_size: 16
instrument_type_insert_size: 16
ints_transform: "none"
# output
mz_max: 1005.
mz_bin_res: 0.1
# model
model_type: "fp_ffn"
mlp_hidden_size: 1024
mlp_dropout: 0.1
mlp_num_layers: 4
mlp_use_residuals: True
ff_prec_mz_offset: 5
ff_bidirectional: True
ff_output_map_size: 256
# optimization
lr: 0.0003
weight_decay: 0.0000001
train_sample_weight: True
eval_sample_weight: True
# other
num_workers: 8
batch_size: 128
drop_last: False
accelerator: "cpu"
log_every_n_steps: 1
max_epochs: 100
seed: 420
enable_checkpointing: False